version: "3.9"
services:
api:
build:
context: ./backend
target: runtime
environment:
NODE_ENV: ${NODE_ENV}
PORT: ${API_PORT}
expose:
- "${API_PORT}"
networks:
- appnet
restart: unless-stopped


web:
build:
context: ./frontend
target: serve
depends_on:
- api
ports:
- "${WEB_PORT}:80" # Expose to host
networks:
- appnet
restart: unless-stopped


networks:
appnet:
driver: bridge
